# Generated by Django 3.0.5 on 2021-01-18 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('lesson', models.CharField(max_length=10)),
                ('module', models.CharField(max_length=10)),
                ('fee_per_hour_per_student', models.IntegerField()),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TutorAid.Course')),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TutorAid.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TutorAid.Student')),
            ],
            options={
                'db_table': 'registration',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('invoiced_at', models.DateField(auto_now_add=True)),
                ('charge', models.IntegerField()),
                ('is_payed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TutorAid.Student')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TutorAid.Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TutorAid.Student')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
