# Generated by Django 3.0.5 on 2021-01-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TutorAid', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'managed': True},
        ),
    ]
