# Generated by Django 3.0.5 on 2021-01-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorAid', '0002_attendance_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
