# Generated by Django 3.0.5 on 2021-01-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorAid', '0003_auto_20210118_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='charge',
            field=models.FloatField(),
        ),
    ]
